//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mancala.Game {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GameInfoResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GameInfoResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mancala.Game.GameInfoResources", typeof(GameInfoResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capturing..
        /// </summary>
        internal static string Capturing {
            get {
                return ResourceManager.GetString("Capturing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capturing and Multiple Laps..
        /// </summary>
        internal static string CapturingAndMultipleLaps {
            get {
                return ResourceManager.GetString("CapturingAndMultipleLaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (Easy)..
        /// </summary>
        internal static string EasyDifficulty {
            get {
                return ResourceManager.GetString("EasyDifficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (Hard)..
        /// </summary>
        internal static string HardDifficulty {
            get {
                return ResourceManager.GetString("HardDifficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Laps..
        /// </summary>
        internal static string MultipleLaps {
            get {
                return ResourceManager.GetString("MultipleLaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (Normal)..
        /// </summary>
        internal static string NormalDifficulty {
            get {
                return ResourceManager.GetString("NormalDifficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s.
        /// </summary>
        internal static string PlayerNameEndsWithSText {
            get {
                return ResourceManager.GetString("PlayerNameEndsWithSText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When one player&apos;s side is empty,
        ///they get the remaining stones..
        /// </summary>
        internal static string PlayerWithEmptySideGetsStones {
            get {
                return ResourceManager.GetString("PlayerWithEmptySideGetsStones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When one player&apos;s side is empty,
        ///the other gets the remaining stones..
        /// </summary>
        internal static string PlayerWithNonEmptySideGetsStones {
            get {
                return ResourceManager.GetString("PlayerWithNonEmptySideGetsStones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;s turn..
        /// </summary>
        internal static string TurnSuffix {
            get {
                return ResourceManager.GetString("TurnSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos; turn..
        /// </summary>
        internal static string TurnSuffixWhenNameEndsWithS {
            get {
                return ResourceManager.GetString("TurnSuffixWhenNameEndsWithS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  vs. .
        /// </summary>
        internal static string Versus {
            get {
                return ResourceManager.GetString("Versus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (Very Hard)..
        /// </summary>
        internal static string VeryHardDifficulty {
            get {
                return ResourceManager.GetString("VeryHardDifficulty", resourceCulture);
            }
        }
    }
}
