//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mancala {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mancala.MessageResources", typeof(MessageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Mancala WPF.
        /// </summary>
        internal static string AboutWindowTitle {
            get {
                return ResourceManager.GetString("AboutWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find clicked cup..
        /// </summary>
        internal static string ClickedCupInvalidMessage {
            get {
                return ResourceManager.GetString("ClickedCupInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tried to take a stone from a cup with no stones..
        /// </summary>
        internal static string CupHasNoStonesMessage {
            get {
                return ResourceManager.GetString("CupHasNoStonesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon from http://ztreasureisle.wikia.com/wiki/File:Green_Stone-icon.png.
        /// </summary>
        internal static string Licenses {
            get {
                return ResourceManager.GetString("Licenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the number of starting stones per cup..
        /// </summary>
        internal static string MissingStonesPerCupMessage {
            get {
                return ResourceManager.GetString("MissingStonesPerCupMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Starting Stones Missing.
        /// </summary>
        internal static string MissingStonesPerCupTitle {
            get {
                return ResourceManager.GetString("MissingStonesPerCupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a name for player 1..
        /// </summary>
        internal static string Player1NameMissingMessage {
            get {
                return ResourceManager.GetString("Player1NameMissingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a name for player 2..
        /// </summary>
        internal static string Player2NameMissingMessage {
            get {
                return ResourceManager.GetString("Player2NameMissingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Name Missing.
        /// </summary>
        internal static string PlayerNameMissingTitle {
            get {
                return ResourceManager.GetString("PlayerNameMissingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to reset all settings to factory defaults?.
        /// </summary>
        internal static string ResetQuestionMessage {
            get {
                return ResourceManager.GetString("ResetQuestionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Settings?.
        /// </summary>
        internal static string ResetQuestionTitle {
            get {
                return ResourceManager.GetString("ResetQuestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  stone..
        /// </summary>
        internal static string StoneSingular {
            get {
                return ResourceManager.GetString("StoneSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  stones..
        /// </summary>
        internal static string StonesPlural {
            get {
                return ResourceManager.GetString("StonesPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game ended with a tie..
        /// </summary>
        internal static string TieMessage {
            get {
                return ResourceManager.GetString("TieMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Over.
        /// </summary>
        internal static string TieTitle {
            get {
                return ResourceManager.GetString("TieTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  wins by .
        /// </summary>
        internal static string WinTextPrefix {
            get {
                return ResourceManager.GetString("WinTextPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Wins.
        /// </summary>
        internal static string WinTitleSuffix {
            get {
                return ResourceManager.GetString("WinTitleSuffix", resourceCulture);
            }
        }
    }
}
